# Generated by Django 4.0.6 on 2022-07-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
