# Generated by Django 4.0.6 on 2022-08-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_councillor_id_person_person_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='link',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='na', upload_to=''),
            preserve_default=False,
        ),
    ]
